/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the caller's profile
         * @description 404 until the first `PUT /me/profile`.
         */
        get: operations["getProfile"];
        /**
         * Create or replace the caller's profile
         * @description Upsert — always succeeds, no 404.
         */
        put: operations["putProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/experience": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List experience entries (most recent first) */
        get: operations["listExperience"];
        put?: never;
        /** Create an experience entry */
        post: operations["createExperience"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/experience/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        /** Get one experience entry */
        get: operations["getExperience"];
        /** Replace one experience entry */
        put: operations["updateExperience"];
        post?: never;
        /** Delete one experience entry */
        delete: operations["deleteExperience"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/education": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List education entries (most recent first) */
        get: operations["listEducation"];
        put?: never;
        /** Create an education entry */
        post: operations["createEducation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/education/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        /** Get one education entry */
        get: operations["getEducation"];
        /** Replace one education entry */
        put: operations["updateEducation"];
        post?: never;
        /** Delete one education entry */
        delete: operations["deleteEducation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List skills (insertion order) */
        get: operations["listSkills"];
        put?: never;
        /** Create a skill */
        post: operations["createSkill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/skills/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        /** Get one skill */
        get: operations["getSkill"];
        /** Replace one skill */
        put: operations["updateSkill"];
        post?: never;
        /** Delete one skill */
        delete: operations["deleteSkill"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/certifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List certifications (insertion order) */
        get: operations["listCertifications"];
        put?: never;
        /** Create a certification */
        post: operations["createCertification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/certifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        /** Get one certification */
        get: operations["getCertification"];
        /** Replace one certification */
        put: operations["updateCertification"];
        post?: never;
        /** Delete one certification */
        delete: operations["deleteCertification"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/hobbies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List hobbies (insertion order) */
        get: operations["listHobbies"];
        put?: never;
        /** Create a hobby */
        post: operations["createHobby"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/hobbies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        /** Get one hobby */
        get: operations["getHobby"];
        /** Replace one hobby */
        put: operations["updateHobby"];
        post?: never;
        /** Delete one hobby */
        delete: operations["deleteHobby"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List goals (insertion order) */
        get: operations["listGoals"];
        put?: never;
        /** Create a goal */
        post: operations["createGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/goals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        /** Get one goal */
        get: operations["getGoal"];
        /** Replace one goal */
        put: operations["updateGoal"];
        post?: never;
        /** Delete one goal */
        delete: operations["deleteGoal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the whole resume in one call
         * @description Assembles the profile plus all six collections in a single query. `format=markdown` returns a rendered Markdown resume instead of JSON.
         */
        get: operations["getResume"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            statusCode?: number;
            message?: string;
        };
        /** @enum {string} */
        EmploymentType: "full-time" | "part-time" | "contract" | "internship" | "self-employed";
        /** @enum {string} */
        SkillCategory: "language" | "framework" | "tool" | "soft-skill";
        /** @enum {string} */
        Proficiency: "beginner" | "intermediate" | "advanced" | "expert";
        /** @enum {string} */
        CertificationType: "professional" | "personal";
        /** @enum {string} */
        GoalCategory: "career" | "personal" | "learning";
        /** @enum {string} */
        GoalStatus: "active" | "achieved" | "abandoned";
        /** @description Fields DynamoDB-backed collection items carry in addition to their own data. */
        ItemMeta: {
            /** Format: uuid */
            id?: string;
            entity_type?: string;
            /** @description Internal DynamoDB partition key (`USER#<clerk_user_id>`). Not needed by clients. */
            pk?: string;
            /** @description Internal DynamoDB sort key (`<ENTITY_TYPE>#<id>`). Not needed by clients. */
            sk?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ProfileMeta: {
            entity_type?: string;
            /** @description Internal DynamoDB partition key (`USER#<clerk_user_id>`). Not needed by clients. */
            pk?: string;
            /** @description Internal DynamoDB sort key (always `PROFILE`). Not needed by clients. */
            sk?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ProfileInput: {
            name: string;
            headline?: string | null;
            summary?: string | null;
            location?: string | null;
            email?: string | null;
            /** @description e.g. `{"linkedin": "...", "github": "...", "site": "..."}` */
            links?: {
                [key: string]: string;
            };
            goals_summary?: string | null;
        };
        Profile: components["schemas"]["ProfileInput"] & components["schemas"]["ProfileMeta"];
        ExperienceInput: {
            organization: string;
            title: string;
            location?: string | null;
            employment_type?: components["schemas"]["EmploymentType"];
            /** Format: date */
            start_date: string;
            /**
             * Format: date
             * @description Omit/null for the current role.
             */
            end_date?: string | null;
            responsibilities?: string[];
            accomplishments?: string[];
        };
        Experience: components["schemas"]["ExperienceInput"] & components["schemas"]["ItemMeta"];
        EducationInput: {
            institution: string;
            degree: string;
            field_of_study?: string | null;
            location?: string | null;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date?: string | null;
            gpa?: string | null;
            honors?: string | null;
            activities?: string | null;
        };
        Education: components["schemas"]["EducationInput"] & components["schemas"]["ItemMeta"];
        SkillInput: {
            name: string;
            category: components["schemas"]["SkillCategory"];
            proficiency?: components["schemas"]["Proficiency"];
            years_experience?: number | null;
        };
        Skill: components["schemas"]["SkillInput"] & components["schemas"]["ItemMeta"];
        CertificationInput: {
            name: string;
            issuing_organization: string;
            /** Format: date */
            issue_date: string;
            /** Format: date */
            expiration_date?: string | null;
            credential_id?: string | null;
            credential_url?: string | null;
            /** @default professional */
            type: components["schemas"]["CertificationType"];
        };
        Certification: components["schemas"]["CertificationInput"] & components["schemas"]["ItemMeta"];
        HobbyInput: {
            name: string;
            description?: string | null;
        };
        Hobby: components["schemas"]["HobbyInput"] & components["schemas"]["ItemMeta"];
        GoalInput: {
            description: string;
            category: components["schemas"]["GoalCategory"];
            /** Format: date */
            target_date?: string | null;
            /** @default active */
            status: components["schemas"]["GoalStatus"];
        };
        Goal: components["schemas"]["GoalInput"] & components["schemas"]["ItemMeta"];
        Resume: {
            profile?: components["schemas"]["Profile"];
            experience?: components["schemas"]["Experience"][];
            education?: components["schemas"]["Education"][];
            skills?: components["schemas"]["Skill"][];
            certifications?: components["schemas"]["Certification"][];
            hobbies?: components["schemas"]["Hobby"][];
            goals?: components["schemas"]["Goal"][];
        };
    };
    responses: {
        /** @description Request body failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, invalid, or expired bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No entry exists for the caller with that id (or no profile yet). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description The entry's `id` (uuid4), as returned by list/create. */
        ItemId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    putProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description The profile as stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listExperience: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Experience entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Experience"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createExperience: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperienceInput"];
            };
        };
        responses: {
            /** @description The created experience entry. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experience"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getExperience: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The experience entry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experience"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateExperience: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperienceInput"];
            };
        };
        responses: {
            /** @description The updated experience entry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experience"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteExperience: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listEducation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Education entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Education"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createEducation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EducationInput"];
            };
        };
        responses: {
            /** @description The created education entry. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Education"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getEducation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The education entry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Education"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateEducation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EducationInput"];
            };
        };
        responses: {
            /** @description The updated education entry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Education"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteEducation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listSkills: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skills. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Skill"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSkill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillInput"];
            };
        };
        responses: {
            /** @description The created skill. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The skill. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillInput"];
            };
        };
        responses: {
            /** @description The updated skill. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listCertifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Certifications. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Certification"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCertification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificationInput"];
            };
        };
        responses: {
            /** @description The created certification. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Certification"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getCertification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The certification. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Certification"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCertification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificationInput"];
            };
        };
        responses: {
            /** @description The updated certification. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Certification"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteCertification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listHobbies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hobbies. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Hobby"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createHobby: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HobbyInput"];
            };
        };
        responses: {
            /** @description The created hobby. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hobby"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getHobby: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The hobby. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hobby"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateHobby: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HobbyInput"];
            };
        };
        responses: {
            /** @description The updated hobby. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hobby"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteHobby: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Goals. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Goal"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createGoal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalInput"];
            };
        };
        responses: {
            /** @description The created goal. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Goal"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The goal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Goal"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalInput"];
            };
        };
        responses: {
            /** @description The updated goal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Goal"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The entry's `id` (uuid4), as returned by list/create. */
                id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getResume: {
        parameters: {
            query?: {
                format?: "json" | "markdown";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The assembled resume. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resume"];
                    "text/markdown": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
